/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package textanalyzer;
import java.util.Map;
import java.util.LinkedHashMap;
/**
 *
 * @author chinmay-kulkarni-ubuntu
 */
public class TextAnalzyerFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextAnalzyerFrame
     */
     private String inputtedText;
    private int textLength;
    private int wordCount;
    private int tabCount;
    private int spaceCount;
    private int lineCount;
    private String uniqueCharString = "";
    public TextAnalzyerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField9 = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label1 = new java.awt.Label();
        Submit = new javax.swing.JButton();
        NumberOfLines = new java.awt.TextField();
        NoOfSpaces = new java.awt.TextField();
        NoOfTabs = new java.awt.TextField();
        LengthOfInpt = new java.awt.TextField();
        NoOfWords = new java.awt.TextField();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();

        textField1.setText("textField1");

        textField9.setText("textField9");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setBackground(new java.awt.Color(255, 51, 51));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label1.setFont(new java.awt.Font("Liberation Mono", 3, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 255, 255));
        label1.setText("              Text-Analyzer");

        Submit.setBackground(new java.awt.Color(255, 0, 0));
        Submit.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        Submit.setForeground(new java.awt.Color(153, 255, 255));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        NumberOfLines.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NumberOfLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfLinesActionPerformed(evt);
            }
        });

        NoOfSpaces.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NoOfSpaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOfSpacesActionPerformed(evt);
            }
        });

        NoOfTabs.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NoOfTabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOfTabsActionPerformed(evt);
            }
        });

        LengthOfInpt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LengthOfInpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthOfInptActionPerformed(evt);
            }
        });

        NoOfWords.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NoOfWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoOfWordsActionPerformed(evt);
            }
        });

        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 0));
        label2.setText("  @ Chinmay Kulkarni");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextField1);

        t.setColumns(20);
        t.setRows(5);
        jScrollPane3.setViewportView(t);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NoOfSpaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumberOfLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NoOfTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NoOfWords, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LengthOfInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberOfLines, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoOfSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoOfTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LengthOfInpt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(NoOfWords, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
         inputtedText = t.getText();

    textLength = inputtedText.length();
    LengthOfInpt.setText("Length of Text = " + textLength);

    wordCount = inputtedText.trim().isEmpty() ? 0 : inputtedText.trim().split("\\s+").length;
    NoOfWords.setText("Words in Text = " + wordCount);

    spaceCount = inputtedText.length() - inputtedText.replace(" ", "").length();
    NoOfSpaces.setText("Spaces in Text = " + spaceCount);

    tabCount = inputtedText.length() - inputtedText.replace("\t", "").length();
    NoOfTabs.setText("Tabs in Text = " + tabCount);
  lineCount= textLength>0?inputtedText.split("\n",-1).length:0;
                NumberOfLines.setText("No.Of lines = "+lineCount);

    Map<Character, Integer> map = new LinkedHashMap<>();

for (char c : inputtedText.toCharArray()) {
    if (!Character.isWhitespace(c)) {
        map.put(c, map.getOrDefault(c, 0) + 1);
    }
}

StringBuilder sb = new StringBuilder("Unique Chars: ");
for (var e : map.entrySet()) {
    sb.append(e.getKey()).append("=").append(e.getValue()).append(", ");
}

if (!map.isEmpty()) sb.setLength(sb.length() - 2); // remove last comma

jTextField1.setText("Unique Characters = "+sb.toString());

    }//GEN-LAST:event_SubmitActionPerformed

    private void NumberOfLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfLinesActionPerformed
        // TODO add your handling code here:
                lineCount= textLength>0?inputtedText.split("\n",-1).length:0;
                NumberOfLines.setText("No.Of lines = "+lineCount);
    }//GEN-LAST:event_NumberOfLinesActionPerformed

    private void NoOfWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOfWordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoOfWordsActionPerformed

    private void LengthOfInptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthOfInptActionPerformed
        // TODO add your handling code here:
        textLength=inputtedText.length();
       
    }//GEN-LAST:event_LengthOfInptActionPerformed

    private void NoOfTabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOfTabsActionPerformed
        // TODO add your handling code here:
        tabCount=inputtedText.split("\t",-1).length-1;
        NoOfTabs.setText("No.Of Tabs = "+tabCount);
    }//GEN-LAST:event_NoOfTabsActionPerformed

    private void NoOfSpacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoOfSpacesActionPerformed
        // TODO add your handling code here:
        spaceCount=inputtedText.split("\s",-1).length-1;
        NoOfSpaces.setText("Spaces in Text = "+ spaceCount);
    }//GEN-LAST:event_NoOfSpacesActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextAnalzyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextAnalzyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextAnalzyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextAnalzyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextAnalzyerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField LengthOfInpt;
    private java.awt.TextField NoOfSpaces;
    private java.awt.TextField NoOfTabs;
    private java.awt.TextField NoOfWords;
    private java.awt.TextField NumberOfLines;
    private javax.swing.JButton Submit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextArea t;
    private java.awt.TextField textField1;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
